apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-wasm-route
spec:
  parentRefs:
  - name: api-gateway
  hostnames:
  - wasm.a2.serpentard.dopolytech.fr
  rules:
  - backendRefs:
    - name: api-wasm
      port: 80
