spin_manifest_version = 2

[application]
name = "api"
version = "0.1.0"
authors = ["Kuruyia <github@kuruyia.net>"]
description = ""

[variables]
db_host = { default = "localhost" }
db_port = { default = "5432" }
db_user = { default = "postgres" }
db_password = { default = "postgres" }
db_name = { default = "postgres" }

[[trigger.http]]
route = "/health"
component = "api"

[[trigger.http]]
route = "/person"
component = "api"

[[trigger.http]]
route = "/person/..."
component = "api"

[component.api]
source = "main.wasm"
allowed_outbound_hosts = ["postgres://{{ db_host }}:{{ db_port }}"]

[component.api.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[component.api.variables]
db_url = "postgres://{{ db_user }}:{{ db_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}"
